import { Hero } from './Hero';

export const HEROES: Hero[] = [
    { id: 1, name: "Elesis", status: "active" },
    { id: 2, name: "Lire", status: "active" },
    { id: 3, name: "Arme", status: "active" },
    { id: 4, name: "Lass", status: "active" },
    { id: 5, name: "Ryan", status: "active" },
    { id: 6, name: "Ronan", status: "active" },
    { id: 7, name: "Amy", status: "active" },
    { id: 8, name: "Jin", status: "active" },
    { id: 9, name: "Sieghart", status: "active" },
    { id: 10, name: "Mari", status: "active" },
    { id: 11, name: "Dio", status: "active" },
    { id: 12, name: "Zero", status: "active" },
    { id: 13, name: "Ley", status: "active" },
    { id: 14, name: "Rufus", status: "active" },
    { id: 15, name: "Rin", status: "active" },
    { id: 16, name: "Asin", status: "active" },
    { id: 17, name: "Lime", status: "active" },
    { id: 18, name: "Edel", status: "active" },
    { id: 19, name: "Veigas", status: "active" },
    { id: 20, name: "Serdin", status: "active" },
    { id: 21, name: "Kanavan", status: "active" },
    { id: 22, name: "Werner", status: "active" },
    { id: 23, name: "Grandiel", status: "active" },
    { id: 24, name: "Nelia", status: "active" },
    { id: 25, name: "Io", status: "active" },
    { id: 26, name: "Hwarin", status: "active" }
];